<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>
    <groupId>io.github.xiaozhug</groupId>
    <artifactId>ai-mcp-bridge-dependencies</artifactId>
    <version>1.0.1</version>

    <packaging>pom</packaging>

    <name>ai-mcp-bridge-dependencies</name>
    <description>ai-mcp-bridge-dependencies</description>
    <url>https://github.com/xiaozhug/ai-mcp-bridge</url>

    <licenses>
        <license>
            <name>The Apache License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
        </license>
    </licenses>

    <scm>
        <connection>scm:git:git://github.com/xiaozhug/ai-mcp-bridge.git</connection>
        <developerConnection>scm:git:ssh://github.com/xiaozhug/ai-mcp-bridge.git</developerConnection>
        <url>https://github.com/xiaozhug/ai-mcp-bridge</url>
    </scm>

    <developers>
        <developer>
            <name>xiaozhug</name>
            <email>532182070@qq.com</email>
            <url>https://github.com/xiaozhug</url>
        </developer>
    </developers>

    <properties>
        <central.publishing.maven.version>0.9.0</central.publishing.maven.version>
        <maven-gpg-plugin.version>3.2.8</maven-gpg-plugin.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.github.xiaozhug</groupId>
                <artifactId>ai-mcp-bridge-apt</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.xiaozhug</groupId>
                <artifactId>ai-mcp-bridge-spring-boot-mcp-adapter-tool-starter</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.xiaozhug</groupId>
                <artifactId>ai-mcp-bridge-spring-boot-mcp-client-starter</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.xiaozhug</groupId>
                <artifactId>ai-mcp-bridge-spring-boot-mcp-file-expose-starter</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.xiaozhug</groupId>
                <artifactId>ai-mcp-bridge-spring-boot-mcp-registry-starter</artifactId>
                <version>${project.version}</version>
            </dependency>

            <dependency>
                <groupId>io.github.xiaozhug</groupId>
                <artifactId>ai-mcp-bridge-spring-boot-mcp-server-expose-starter</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.sonatype.central</groupId>
                <artifactId>central-publishing-maven-plugin</artifactId>
                <version>${central.publishing.maven.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <publishingServerId>central</publishingServerId>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>${maven-gpg-plugin.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                        <phase>verify</phase>
                        <configuration>
                            <gpgArguments>
                                <arg>--pinentry-mode</arg>
                                <arg>loopback</arg>
                            </gpgArguments>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
