<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.github.xiaozhug</groupId>
        <artifactId>ai-mcp-bridge</artifactId>
        <version>${revision}</version>
        <relativePath>../../pom.xml</relativePath>
    </parent>

    <artifactId>ai-mcp-bridge-spring-boot-mcp-registry-starter</artifactId>
    <name>ai-mcp-bridge-spring-boot-starters :: ai-mcp-bridge-spring-boot-mcp-registry-starter</name>
    <description>ai-mcp-bridge-spring-boot-mcp-registry-starter</description>
    <url>https://github.com/xiaozhug/ai-mcp-bridge</url>

    <scm>
        <connection>scm:git:git://github.com/xiaozhug/ai-mcp-bridge.git</connection>
        <developerConnection>scm:git:ssh://github.com/xiaozhug/ai-mcp-bridge.git</developerConnection>
        <url>https://github.com/xiaozhug/ai-mcp-bridge</url>
    </scm>

    <developers>
        <developer>
            <name>xiaozhug</name>
            <email>532182070@qq.com</email>
            <url>https://github.com/xiaozhug</url>
        </developer>
    </developers>

    <dependencies>
        <dependency>
            <groupId>io.github.xiaozhug</groupId>
            <artifactId>ai-mcp-bridge-autoconfigure-mcp-registry</artifactId>
            <version>${revision}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

</project>
